config/routes.rb
FbSearchApp::Application.routes.draw do
  resources :fb_searches, :except => [:edit, :update]

  root :to => "FbSearches#new"

end

app/models/fb_search.rb
class FbSearch < ActiveRecord::Base
  attr_accessible :keywords, :search_type

  validates :keywords, :presence => true
  validates :search_type, :inclusion => { :in => FacebookApi::TYPES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fb_searches_controller.rb
class FbSearchesController < ApplicationController
  def new
    @fb_search = FbSearch.new
  end

  def create
    @fb_search = FbSearch.find_or_create_by_keywords_and_search_type(params[:fb_search])
    if @fb_search.save
      @fb_search.increment!(:frequency)
      redirect_to fb_search_path(@fb_search)
    else
      render 'new'
    end
  end

  def show
    @fb_search = FbSearch.find(params[:id])
    @other_attr = other_attr(@fb_search.search_type)
    search = FacebookApi::Search.new.data(@fb_search.keywords, @fb_search.search_type)
    @results = create_type_objs(search, @fb_search.search_type)
  end

  def index
    @fb_searches = FbSearch.order("frequency DESC LIMIT 20").all
  end

  def destroy
    FbSearch.find(params[:id]).destroy
    redirect_to fb_searches_path
  end

  private

    def create_type_objs(search, type)
      case type
      when "post"
        search.map { |data| FacebookApi::Post.new(data) }
      when "user"
        #search.map { |data| FacebookApi::Person.new(data) }
      when "event"
        #search.map { |data| FacebookApi::Event.new(data) }
      when "application"
        search.map { |data| FacebookApi::Application.new(data) }
      when "group"
        search.map { |data| FacebookApi::Group.new(data) }
      else
        search.map { |data| FacebookApi::Page.new(data) }
      end
    end

    def other_attr(type)
      case type
      when "post"
        "user"
      when "user"
      when "event"
      when "application"
        "namespace"
      when "group"
        "version"
      else
        "category"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fb_searches_helper.rb
module FbSearchesHelper
end

app/views/fb_searches/index.html.erb
<h1>Recent Searches</h1>
<%= link_to 'Back to new search', new_fb_search_path %><br /><br />
<table>
  <tr>
    <th>Keywords</th>
    <th>Search made...</th>
    <th>Frequency</th>
    <th>Type</th>
    <th>Delete</th>
  </tr>
  <% @fb_searches.each do |search| %>
    <tr>
      <td><%= link_to search.keywords, fb_search_path(search), :class => "search" %> </td>
      <td><%= timeago_tag search.updated_at %></td>
      <td><%= search.frequency %></td>
      <td><%= search.search_type %></td>
      <td><%= link_to 'remove', search, :method => :delete, :confirm => "Delete search from history?" %></td>
    </tr>
  <% end %>
</table>

app/views/fb_searches/new.html.erb
<h1>Facebook Search</h1>
<%= link_to "View recent searches", fb_searches_path %><br /><br />
<%= form_for(@fb_search) do |f| %>
  <%= f.label :keywords %><br />
  <% if @fb_search.errors.any? %>
    <% @fb_search.errors.full_messages.each do |msg| %>
      <span class="error"><%= msg %></span><br />
    <% end %>
  <% end %>
  <%= f.text_field :keywords %><br />
  <%= f.label :search_type, "Type" %><br />
  <%= f.select :search_type, FacebookApi::TYPES %><br />

  <%= f.submit "Search" %>
<% end %>

app/views/fb_searches/show.html.erb
<h1>Search Results: <%= @fb_search.keywords %></h1>
<%= link_to "Back to new search", root_path %><br /><br />
<table>
  <tr>
    <th><%= @other_attr ? @other_attr.capitalize : "Error" %></th>
    <th><%= @fb_search.search_type.capitalize %></th>
  </tr>
  <% if @fb_search.search_type === "post" %>
    <% @results.each do |post| %>
      <% if post.message %>
        <tr>
          <td class="user">
            <%= image_tag post.author.picture.get, :alt => post.author.name %>
            <%= link_to post.author.name, "https://www.facebook.com/#{post.author.id}", :target => "_blank" %><br />
            <%= timeago_tag Time.parse(post.created_time) %>
          </td>
          <td class="post">
            <% if post.message.length <= 150 %>
              <%= post.message %>
            <% else %>
              <%= post.message[0...150] %>...
              <%= link_to "read more", "", :class => "show_modal" %>
              <div class="modal"><%= post.message %></div>
            <% end %>
            <% if post.picture %>
              <%= image_tag post.picture.get, :alt => "Photo for #{post.name || 'post'}" %>
            <% end %>
            <%= link_to "View on Facebook...", "https://www.facebook.com/#{post.id}", :target => "_blank", :class => "external" %>
          </td>
        </tr>
      <% end %>
    <% end %>
  <% elsif @fb_search.search_type === "group" || @fb_search.search_type === "application" || @fb_search.search_type === "page" %>
    <% @results.each do |result| %>
      <tr>
        <td class="<%= @other_attr %>"><%= result.other_attr %></td>
        <td class="<%= @fb_search.search_type %>">
          <%= image_tag result.picture.get, :alt => result.name %>
          <%= link_to result.name, "https://www.facebook.com/#{result.id}", :target => "_blank" %>
        </td>
      </tr>
    <% end %>
  <% else %>
    <tr><td>Login required to perform this search!</td><td>&nbsp;</td></tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FbSearchApp</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= yield %>

    <div class="footer">
      <hr />
      <p>2013, Created by Michael Rose</p>
    </div>
  </body>
</html>